# version: '3.8'

# services:
#   app:
#     build: .
#     container_name: node_app
#     ports:
#       - "8001:8001" 
#     depends_on:
#       - mongo
#     networks:
#       - app-network

#   mongo:
#     image: mongo:6
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db
#     networks:
#       - app-network
#     environment: 
#       MONGO_URI: mongodb://mongo:27017/MyData


# networks:
#   app-network:

# volumes:
#   mongo-data:
